- src/api/controllers/SignupController.ts
- src/apps/settings/apps/newsletters/app.ts
- src/apps/settings/apps/newsletters/views/report.pug
- src/core/defaults.json
- src/core/providers/email/MandrillProvider.ts
- src/core/providers/newsletter/MailchimpProvider.ts
- src/core/providers/newsletter/NoneProvider.ts
- src/core/providers/newsletter/index.ts
- src/core/services/GCPaymentWebhookService.ts
- src/core/services/MembersService.ts
- src/core/services/NewsletterService.ts
- src/tools/mailchimp/sync.ts
- src/webhooks/mailchimp.ts
Improvements from https://github.com/thebristolcable/beabee/pull/20 https://github.com/thebristolcable/beabee/pull/21 https://github.com/thebristolcable/beabee/pull/22
- Fix Mailchimp 404s
- Sync groups
- Show resync report
> Mailchimp improvements

- src/apps/members/app.ts
- src/apps/members/apps/member/app.ts
- src/apps/members/apps/member/apps/contribution/app.ts
- src/apps/members/apps/member/apps/contribution/views/gocardless.pug
- src/apps/members/apps/member/apps/permissions/app.ts
- src/apps/members/apps/member/apps/permissions/views/index.pug
- src/apps/members/apps/member/views/partials/profile.pug
- src/apps/members/apps/member/views/partials/sidebar.pug
- src/apps/members/views/partials/search.pug
- src/apps/settings/apps/content/app.ts
- src/apps/settings/apps/content/config.json
- src/apps/tools/apps/exports/exports/EditionExport.ts
- src/core/services/MembersService.ts
- src/core/services/PollsService.ts
- src/core/template-locals.ts
- src/models/PollResponse.ts
- src/views/partials/permission.pug
- src/webhooks/mailchimp.ts
- Fix trying to update an old email address
- Add sorting options to members table
- Give more access to admin so less people need superadmin
- Other little bug fixes
> Downstream changes from the Cable

- src/apps/polls/app.ts
- src/apps/polls/config.json
- src/apps/polls/views/ballot.pug
- src/apps/polls/views/login.pug
- src/apps/polls/views/poll.pug
- src/apps/polls/views/thanks.pug
- src/apps/tools/apps/exports/exports/EditionExport.ts
- src/apps/tools/apps/notices/app.ts
- src/apps/tools/apps/polls/app.ts
- src/apps/tools/apps/polls/views/partials/poll-form.pug
- src/apps/tools/apps/polls/views/poll.pug
- src/core/defaults.json
- src/core/services/PollsService.ts
- src/core/utils/polls.ts
- src/migrations/1624370860614-AddPollResponsePassword.ts
- src/migrations/1639760915487-AddAllowMultiplePollResponses.ts
- src/models/Poll.ts
- src/models/PollResponse.ts
- src/static/scss/_general.scss
- src/views/base.pug
- src/views/mixins.pug
- Only anonymous polls
- Allow multiple answers per user
- Allow responses to be password protected
- Replicate callouts
- Make polls embeddable
- Add ability to clear poll responses
> Poll changes from the Cable

- package-lock.json
- package.json
- src/api/controllers/MemberController.ts
- src/api/data/ContributionData.ts
- src/api/data/MemberData.ts
- src/apps/members/apps/member/apps/contribution/app.ts
- src/apps/members/apps/member/apps/contribution/views/gocardless.pug
- src/apps/members/apps/member/views/partials/contribution.pug
- src/core/services/GCPaymentService.ts
- src/core/services/PaymentService.ts
- src/core/utils/index.ts
- src/core/utils/payment.ts
- src/models/Member.ts
Backend changes to support https://github.com/beabee-communityrm/beabee-frontend/pull/83
> Prorate contribution changes

- src/apps/projects/app.ts
- src/apps/settings/apps/content/views/index.pug
- src/apps/tools/apps/polls/app.ts
* Fix no project owner on creation
* Allow join subtitle to have HTML
* Fix callout response exports sometimes not having FirstName or LastName column
> Fixes from Cable

- src/api/app.ts
- src/api/controllers/MemberController.ts
- src/api/controllers/SegmentController.ts
- src/api/data/MemberData.ts
- src/api/utils/members.ts
- src/apps/members/app.ts
- src/apps/members/apps/segments/app.ts
- src/core/services/SegmentService.ts
- src/core/template-locals.ts
- src/core/utils/rules.ts
- src/models/Member.ts
- src/tools/process-segments.ts
Backend changes for https://github.com/beabee-communityrm/beabee-frontend/pull/89
> Contact list APIs

- src/api/controllers/ContentController.ts
- src/core/utils/email.ts
Add simple API to get the email footer
> feat: add email content for footer

- src/api/controllers/ContentController.ts
- src/core/defaults.json
Load theming from `content/general`, most of the work is done in https://github.com/beabee-communityrm/beabee-frontend/pull/228
> feat: add option for dynamic theming

- src/api/controllers/ContentController.ts
- src/core/services/OptionsService.ts
* Use PATCH update rather than PUT overwrite
* Handle getting/setting `Options` generically
> Content API improvements

- src/api/controllers/CalloutController.ts
- src/core/services/CalloutsService.ts
Move `createCallout` to the service and remove the abstract `CalloutAdminController` in favour of all the routes being in `CalloutController`. This was originally an attempt to separate admin only roles but in practice it hasn't been very useful
> refactor: clean up CalloutController

- Dockerfile
Addresses recent Synk security notifications
> build: upgrade Docker image dependencies

- src/core/providers/payment/StripeProvider.ts
Because we use anonymised data for development Stripe won't recognise the mandate ID when we try to fetch it. Let this fail silently on dev, it will just assume there is no payment method
> fix: allow fetching mandate to 404 on dev

- src/api/controllers/CalloutController.ts
- src/api/controllers/ContactController.ts
- src/api/data/CalloutResponseData/interface.ts
- src/api/data/ContactData/index.ts
- src/api/data/PaginatedData/interface.ts
- src/core/services/PaymentService.ts
- src/models/Contact.ts
- src/models/PaymentData.ts
Add a new endpoint to export contacts
* `GET /contacts.csv`: export contacts, can apply a `RuleGroup` as a query parameter to filter contacts
> feat: add export contacts endpoint

- package-lock.json
- package.json
- src/api/data/CalloutResponseData/index.ts
- src/api/data/PaginatedData/index.ts
Add support for the answers filter so you can now search across all the text in a callout response.
> feat: add answers filter

- Dockerfile
Fixes various curl vulnerabilities reported by Snyk
> build: upgrade nginx to fix vulnerabilities

- package-lock.json
- package.json
- src/api/data/CalloutResponseData/index.ts
- src/api/data/CalloutResponseData/interface.ts
- src/apps/polls/app.ts
- src/core/services/CalloutsService.ts
- src/models/CalloutResponse.ts
- src/tools/database/anonymisers/index.ts
- src/tools/database/anonymisers/models.ts
Extract the title and photo properties on the server side for the /map endpoint. At the moment these props are hardcoded but they will be configurable
> feat: callout gallery view

- package-lock.json
- package.json
- src/api/data/CalloutResponseData/index.ts
Filter only responses to adminOnly components on the public /map endpoint
> feat: support for adminOnly callout components

- src/apps/projects/app.ts
> fix: add contacts to project

- src/core/data/email/confirm-email_pt.yfm
- src/core/data/email/email-exists-login_pt.yfm
- src/core/data/email/email-exists-set-password_pt.yfm
- src/core/data/email/manual-to-automatic_pt.yfm
- src/core/data/email/reset-device_pt.yfm
- src/core/data/email/reset-password_pt.yfm
Create new transactional emails in Portuguese.
> Translate transactional emails to Portuguese

- package-lock.json
- package.json
- src/api/controllers/CalloutController.ts
- src/api/controllers/ContactController.ts
- src/api/decorators/CalloutId.ts
- src/api/decorators/TargetUser.ts
- src/api/dto/CalloutDto.ts
- src/api/params/CalloutResponseParams.ts
- src/api/transformers/BaseCalloutResponseTransformer.ts
- src/api/transformers/CalloutResponseExporter.ts
- src/api/transformers/CalloutResponseMapTransformer.ts
- src/api/transformers/CalloutResponseTransformer.ts
- src/api/transformers/CalloutTransformer.ts
- src/apps/tools/apps/polls/app.ts
- src/core/services/CalloutsService.ts
- src/migrations/1708615794655-AddCalloutId.ts
- src/models/Callout.ts
- src/models/CalloutResponse.ts
- src/models/CalloutTag.ts
- src/tools/database/anonymisers/index.ts
- src/tools/database/export-demo.ts
Adds a stable callout ID which can be used for foreign key references etc. as the slug can change
> feat: add callout ID field

- src/core/services/ContactsService.ts
Not sure why this fixes it, seems like a bug in TypeORM
> fix: duplicate key on update contact role

- package-lock.json
- package.json
- src/core/utils/payment/gocardless.ts
- src/core/utils/payment/stripe.ts
- src/webhooks/handlers/stripe.ts
Same as #414 but merged into master
> feat: add new draft payment status

- README.md
- src/api/dto/CalloutDto.ts
- src/api/transformers/CalloutTransformer.ts
- src/core/services/CalloutsService.ts
- src/enums/callout-channel.ts
- src/migrations/1715184967411-callout-channels.ts
- src/models/Callout.ts
- src/type/callout-data.ts
Adds callout channels (#412) for the v0.14.x release branch
> feat: callout channels for v0.14.x
