src/api/controllers/MemberController.ts, src/api/data/MemberData.ts
- Added `with` query param to only return profile when needed
- Added new data to get/edit profile
- Changed PUT /member/me to PATCH for consistency
Update member:
`PUT /member/me` -> `PATCH /member/me`
Get member
`GET /member/me` -> no change
Get member with profile
`GET /member/me` -> `GET /member/me?with[]=profile`
=> feat: add profile get/push to endpoints

src/api/controllers/SegmentController.ts, src/api/data/MemberData.ts, src/api/utils/members.ts, src/api/utils/pagination.ts, src/core/utils/newRules.ts
Add support for some special fields for member queries as although they aren't visible in the new UI they are still used in segments created in the legacy app so it needs to work.
This is all quite hacky and mostly involves copying code from the old rules parser to the `fetchPaginatedMembers` method. We should revisit this when we look at how to make advanced search work going forwards
=> chore: support special fields for member search as segments already use them

src/core/lib/gocardless.ts, src/core/providers/payment/index.ts, src/core/services/GCPaymentService.ts, src/core/services/JoinFlowService.ts
The start of the Stripe integration:
* Use singleton pattern for `GCPaymentService` so it can inherit it's interface from `PaymentProvider`
* Abstract away from directly using GoCardless data structures (e.g. `prefilled_customer`) outside of GC services
=> Stripe integation: GC abstraction

src/api/controllers/MemberController.ts, src/api/controllers/SignupController.ts, src/core/providers/payment/index.ts, src/core/services/GCPaymentService.ts, src/core/services/JoinFlowService.ts, src/core/services/PaymentService.ts, src/core/services/StripePaymentService.ts, src/core/utils/index.ts, src/migrations/1650900384747-AddPaymentMethodToJoinForm.ts, src/migrations/1650904701374-NonNullRedirectFlowId.ts, src/models/JoinFlow.ts, src/models/JoinForm.ts
Move all `GCPaymentService` calls to within `PaymentService` and create the stub `StripePaymentService`. This is a no-op change to live environments as there is no way of selecting the Stripe payment route, but it creates a layer of abstraction between GoCardless and the rest of the code to begin implementing Stripe payments
=> Stripe integration: add stub Stripe payment provider

src/api/controllers/MemberController.ts, src/api/controllers/SignupController.ts, src/apps/gift/app.ts, src/apps/login/app.ts, src/apps/members/apps/add/app.ts, src/apps/members/apps/member/apps/contribution/app.ts, src/core/providers/payment/index.ts, src/core/services/GCPaymentService.ts, src/core/services/GCPaymentWebhookService.ts, src/core/services/GiftService.ts, src/core/services/MembersService.ts, src/core/services/PaymentService.ts, src/core/services/StripePaymentService.ts, src/core/utils/member.ts
A few small changes and a refactor so `PaymentService` (and providers) don't have a dependency on `MembersService`. Currently the `PaymentService` directly modifies contribution related fields on a member, this should be handled by the `MembersService`.
=> Improvements to MembersService

src/api/controllers/CalloutController.ts, src/api/data/CalloutData.ts, src/apps/settings/apps/content/views/index.pug, src/apps/share/app.ts, src/apps/share/config.json, src/apps/share/views/index.pug, src/core/services/PageSettingsService.ts, src/migrations/1652276361695-AddShareFieldsToPoll.ts, src/models/Poll.ts
1. Adds the share title/description fields to the `Poll` model and equivalent API routes
2. Adds a new route `/share` which just responses with the things crawlers want to know.
The legacy app has a model called `PageSettings` which has historically been used to override these settings, for backwards compatibility the `/share` route will continue to support these
=> Add share/description for callouts

package-lock.json, package.json, src/api/controllers/CalloutController.ts, src/api/data/CalloutData/index.ts, src/api/data/CalloutData/interface.ts, src/api/data/ContactData/index.ts
A few improvements to the callout responses API
* Added the `id` to the callout response data
* Added a new route `/callout/<slug>/responses/<id>` to fetch an individual response.
* Introduce `with` query param for fetching responses
* `answers`: add the `answers` field to the response
* `contact`: add an expanded `contact` field to the response
* Bumped `beabee-common` to add `createdAt` and `updatedAt` as fields that can be filtered on when paginating over responses.
=> feat: improved callout responses API

Dockerfile
Node modules are now copied from the build stage instead of re-installed. Solves a problem with muhammara and should make the build quicker.
=> Copy and prune node modules in container

package-lock.json, package.json, src/api/controllers/CalloutResponseController.ts, src/api/controllers/ContactController.ts, src/api/controllers/NoticeController.ts, src/api/data/CalloutData/index.ts, src/api/data/CalloutResponseData/index.ts, src/api/data/CalloutResponseData/interface.ts, src/api/data/ContactData/index.ts, src/api/data/PaginatedData/index.ts, src/api/data/PaginatedData/interface.ts, src/core/services/SegmentService.ts, src/migrations/1676460782435-AddCalloutResponseBucket.ts, src/models/CalloutResponse.ts
Adds the bucket field to the `CalloutResponse` table and creates a new endpoint for batch updating callout responses. It uses a new `batchUpdate` method which works similarly to `fetchPaginated` by taking a `RuleGroup` which defines what will be updated.
Previous `fetchPaginated` aliased the main database table you were fetching as `item` to make it it simple to add more clauses to the query, e.g.
```
qb.where("item.id = :id")
```
TypeORM then takes care of mapping columns to their database names. Unfortunately TypeORM doesn't support alias on updates (https://github.com/typeorm/typeorm/issues/1798) so I rewrote the code to accept a `fieldPrefix` argument which can be empty so that the target table in the UPDATE query is not aliased.
All this means that we can use the same powerful …
=> feat: add response bucket and batch updating

package-lock.json, package.json, src/api/controllers/CalloutController.ts, src/api/data/CalloutResponseData/index.ts, src/api/data/CalloutResponseData/interface.ts, src/api/data/CalloutTagData/index.ts, src/api/data/CalloutTagData/interface.ts, src/api/data/PaginatedData/index.ts, src/migrations/1676654870090-AddCalloutTag.ts, src/migrations/1676655715419-AddCalloutResponseTag.ts, src/models/CalloutResponse.ts, src/models/CalloutResponseTag.ts, src/models/CalloutTag.ts
This PR introduces the schema changes and necessary endpoints to tag callout responses.
A callout has a list of valid tags (`CalloutTag` model) and a response can be tagged with one of these (`CalloutResponseTag` model).
* `GET /callout/:slug/tags`: Get list of possible tags for a callout
* `POST /callout/:slug/tags`: Add a new tag for a callout
* `PATCH /callout/:slug/tags/:id` Updates a tag
`PATCH /callout-responses`: This endpoint can now add or remove tags from callout responses
Each tag ID in the new `tags` property on `UpdateCalloutResponseData` should be preceded by a `+` or `-` which indicates whether to add or remove the tag respectively.
e.g. Add tag1 and remove tag2 for all callout responses in the verified bucket
```json
{
"rules": {"condition": "AND", "rules": [{"field": …
```
=> feat: add callout response tags

src/api/controllers/CalloutController.ts, src/api/data/CalloutResponseData/index.ts, src/api/data/CalloutResponseData/interface.ts, src/api/data/PaginatedData/index.ts, src/apps/tools/apps/polls/app.ts
New endpoint to export all or a filtered subset of a callout's responses.
* `GET /callout/:slug/responses.csv`: Download a callout's responses as a CSV
This endpoint accepts the same `rules` query parameter as paginated endpoints to filter for a subset of responses
=> Add endpoint to export responses

.github/workflows/deploy.yml, .github/workflows/release.yml
This PR adds version tagging to Docker images. Any Git tags which match `v*` will now create an equivalent tag in Docker, the `release` Docker tag will continue to be updated.
It also triggers hive deployment by pushing an updated docker-compose.yml file (with latest tags) to a repo, which our Portainer instance polls then updates the stack. This is currently being tested (hence the repo is called test-deploy)
=> feat: new deployment strategy

src/api/data/ContactData/index.ts, src/api/data/PaginatedData/index.ts
- Always sort null values to the bottom (could be configurable in the future?).
- Clean up sort specific contact logic
=> chore: more intuitive contact sorting

src/api/controllers/CalloutController.ts
It should only try to set `formSchema` if it exists in the request data
=> fix: update callout always trying to set formSchema

src/tools/configure.ts, src/tools/new-user.ts
Added a `tools/configure` script to set some options that are still a bit complicated to change in the UI, and added the option to generate a reset password link to `tools/new-user` (useful when an email provider hasn't been set yet)
=> feat: new and update tools for a simpler setup process

nginx.conf
Remove gzip from here in favour of it being enabled in the main router, see https://github.com/beabee-communityrm/beabee-router/pull/10
=> chore: enable gzip globally

src/core/utils/payment/stripe.ts
Previous implementation assumed that all period lengths (end - start) would be divisible by 12 because they were made up of whole days, but this isn't necessarily true for manual contributions
=> fix: round protation time to nearest second

src/core/services/EmailService.ts, src/locales/current.ts
We added NL with limited translations (for CNR mode), so just fallback to EN for emails and other translations
=> fix: add NL and fallback to EN for emails

src/migrations/1706113195469-ConvertChargeDateToDate.ts, src/models/Payment.ts
It turns out the type of `chargeDate` has been wrong for a while, it was being returned from TypeORM as a string. This is because the date database field doesn't map onto Date (it has no time). This was a legacy of the GoCardless only payment service as payments only have a date in GoCardless, but now we support Stripe we should be using datetimes anyway.
=> fix: chargeDate was actually a string, should be a Date

.env.example, src/api/middlewares/AuthMiddleware.ts, src/config/config.ts, src/core/server.ts, src/core/services/NetworkCommunicatorService.ts, src/core/services/OptionsService.ts, src/core/utils/auth.ts
Implement JWT for internal communication to make it more secure.
This is currently untested because we need to implement the verification for the other services first and then we need to test this on Portainer.
* A new environment variable `BEABEE_SERVICE_SECRET` is required
=> More secure internal communication

docker-compose.yml
Mailhog hasn't been updated since 2020 and maildev looks more stable. This doesn't really matter for development but this is a partly test to use this tool for dev/demo stages as Mailhog had some security issues in a recent pen test
=> fix: use maildev instead of mailhog for development

src/api/dto/CalloutDto.ts, src/api/dto/CalloutFormDto.ts, src/api/interceptors/ValidateResponseInterceptor.ts
This has been less successful than I hoped. I started adding validation to the form schema but hit against the wall of FormIO component schemas. Unfortunately components have so many possible properties that I don't think I could be fully sure I'm validating it correctly without a lot more work.
So this adds some validation, more than there was before, but disables whitelist validation for components. That means it will check the properties it knows about, but will let other ones through unchecked.
=> feat: validate callout form schema

src/api/controllers/CalloutController.ts, src/api/decorators/TargetUser.ts, src/api/utils/index.ts, src/api/validators/IsVariantsObject.ts, src/core/services/CalloutsService.ts, src/models/Callout.ts
Add a new API endpoint to use copy from another callout when creating a new one, allowing easy duplication of callouts.
=> feat: replicate callout in API

src/api/transformers/BaseCalloutResponseTransformer.ts, src/api/transformers/BaseContactTransformer.ts, src/api/transformers/BaseTransformer.ts, src/api/transformers/CalloutResponseTransformer.ts, src/api/transformers/CalloutTransformer.ts, src/api/transformers/ContactExporter.ts, src/api/transformers/ContactTransformer.ts, src/api/utils/rules.ts, src/type/filter-handlers.ts
This PR adds the ability to filter contacts by their answers to a callout. An example of a filter rule is:
```json
{
"field": "callouts.<calloutId>.responses.answers.<slideId>.<componentId>",
"operator": "equal",
"value": ["test"]
}
```
The filter fields are exactly the same as those already supported for callout response filtering, but with the prefix `callouts.<calloutId>.responses`. Indeed it reuses the same code, the contact field handler strips the prefix and delegates the filtering logic to `individualAnswerFilterHandler`.
This PR also includes the following refactoring:
* To support the changes `BaseTransformer.transformFilters` has become an async function
* `BaseContactTransformer` as a new base class for `ContactTransformer` and `ContactExporter`. This reduces duplication and a …
=> feat(contact-filters): contact callout response filters

src/api/transformers/BaseContactTransformer.ts, src/api/transformers/ContactExporter.ts, src/api/transformers/ContactTransformer.ts, src/apps/tools/apps/exports/exports/ActiveMembersExport.ts, src/core/providers/payment/GCProvider.ts, src/core/providers/payment/ManualProvider.ts, src/core/providers/payment/StripeProvider.ts, src/core/providers/payment/index.ts, src/core/services/PaymentService.ts, src/migrations/1713373413805-RenamePaymentDataToContactContribution.ts, src/models/Contact.ts, src/models/ContactContribution.ts, src/tools/database/anonymisers/models.ts, src/tools/database/export-demo.ts, src/tools/database/export.ts, src/tools/gocardless/migrate-to-stripe.ts, src/tools/stripe/resync.ts, src/tools/test-users.ts, src/webhooks/handlers/stripe.ts, src/webhooks/utils/gocardless.ts
This PR is the first in a series aimed at refactoring the payment code. This first one is simple: give the table a better name. The table should always have been `ContactSomething` as it's dependent on a `Contact` object, and `Contribution` is a much clearer name than `PaymentData`
=> refactor(contribution): rename PaymentData to ContactContribution

package-lock.json, package.json, src/api/transformers/BaseContactTransformer.ts, src/api/utils/index.ts
Add a new filter to query for contacts that have answered a callout, rather than the more specific filters introduced in #392 which were about querying the specific answers to callouts
=> feat(contact-filters): add filter for if contact has answered the callout or not

package-lock.json, package.json, src/core/utils/payment/gocardless.ts, src/core/utils/payment/stripe.ts, src/webhooks/handlers/stripe.ts
We currently give payments that have yet to be initiated and those that are being processed the same status of `pending`. On Stripe this means that draft invoices get categorised as pending, even though they will never be processed, and the same thing for GoCardless payments in state pending customer approval.
This PR introduces a new status, `draft`, to distinction between the two. Initially this is so we can filter payments on the frontend and not show users really old draft payments that will never be submitted.
=> feat: add new draft payment status

src/webhooks/handlers/stripe.ts
If we already have the payment on file we should update it regardless of if we can find a corresponding contribution or not. This is a bit of an edge case, but can happen when a user creates a new customer but there is a retrospective update to a payment
=> fix: payment status updates being missed
